number and string dataset
toreda/rocketlab pull request #3
Opened 2021-02-04 20:41 UTC by azadeh-toreda

2021-02-09 20:38 UTC, mbrich requested changes

2021-02-09 20:38 UTC, mbrich commented on src/datasets/strings.ts
> +export interface StringItem {
We spoke about this briefly a few days ago, but I think we can improve type checking here by replacing per-file `XXXXItem` with a single `DatasetsItem<T>` interface.
Implementation steps:
* Create `src/datasets/item.ts` which exports interface `DatasetsItem<T>`
* Update all exported values to define a type. 
* Remove the `StringItem` interface and all other type-specific interfaces and replace their usage with `DatasetsItem<T>`.

2021-02-09 20:38 UTC, mbrich commented on src/datasets/strings.ts
> +export const EMPTY_STRING = { label: 'empty-string', value: '' };
After adding the `DatasetsItem<T>` specified above, update all exports in this file with the expected type. This will help tremendously with IDE type hints.
The new type will look something like:
```typescript
export const EMPTY_STRING: DatasetItem<string> = ...
```

2021-02-09 20:38 UTC, mbrich commented on src/datasets/strings.ts
> +    value: any;
Updating this interface to use the generic will look like:
```typescript
value: any
```
will become:
```typescript
value: T
```

2021-02-09 20:38 UTC, mbrich commented on src/datasets/strings.ts
> +export const EMOJI_SINGLE = [
For emoji values, replace codes here with single character emoji characters from this list:
https://unicode.org/emoji/charts/full-emoji-list.html

Unicode has become more commonly available than it used to be. Apps used to implement emojis using character replacement, but now the common set of emojis are actual string characters that can be copy and pasted into text, because the emojis exist as unique characters in the unicode standard. We use this set to test units which should or should not handle emoji characters.

2021-02-09 20:38 UTC, mbrich commented on src/datasets/strings.ts
> +export const EMOJI_MULTI = [
Same feedback as above in EMOJI_SINGLE. Replace emoji codes with emoji characters from: https://unicode.org/emoji/charts/full-emoji-list.html

2021-02-11 17:52 UTC, azadeh-toreda commented on src/datasets/strings.ts
> +export interface StringItem {
Should I use generic interface for boolean.ts as well?

2021-04-06 20:26 UTC, merged